spring:
  application:
    name: aftersight
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/after_sale_platform?serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: kaduoxi2


  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  profiles:
    active: dev
#  main:
#    allow-bean-definition-overriding: true
aliyun:
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    access-key-id: yourOSS_ACCESS_KEY_ID
    access-key-secret: yourOSS_ACCESS_KEY_SECRET
    bucket-name: tklias
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true          #   页码小于1查第一页，大于总页数查最后一页
  supportMethodsArguments: true   #   允许把分页参数直接放到 Mapper 方法参数里
  params: count=countSql    #   用于自定义 count 统计 SQL，优化大表分页计数